
services:
  db:
    image: postgres:15-alpine
    container_name: closset_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: closset
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # This loads the init.sql file automatically on the first run
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql